### ISSUE TITLE
HomePod?

### ISSUE THREAD

**Issue by vespino** [jamesdlow/open-airplay#25]
Can this project be used to stream a live radio stream to my HomePod from the Ubuntu command line?

**Comment by cjbirk** [comment]
I'm also interested in the answer here. I would assume you can

**Comment by vespino** [comment]
I was able to solve my "problem" by applying Synology's Audio Station. This has airplay support built in and can be controlled from the command line. My goal was to not have to turn on and off my HomePods every day and have them switch to different streams during the day. I hate unnecessary repetitive actions when they can be easily automated.
